apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-dpl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: dev
  template:
    metadata:
      name: dev-pod
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: aminebou/mycicd:v1.0  

---

apiVersion: v1
kind: Service
metadata:
  name: dev-srv
spec:
  type: NodePort
  selector:
    app: dev
  ports:
    - port: 5000
      targetPort: 5000 # cible l'application serveur conteneurisé dans le Pod référencé
      nodePort: 30007