apiVersion: v1
kind: Service
metadata:
  name: prod-srv
spec:
  type: NodePort
  selector:
    app: prod
  ports:
    - port: 5000
      targetPort: 5000 # cible l'application serveur conteneurisé dans le Pod référencé
      nodePort: 30009
