IMAGE_NAME = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = IMAGE_NAME

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "serveur-jenkins"
  end

  # Provision
  config.vm.provision :shell, :path => 'ubuntu-install_ansible.sh'
  config.vm.provision :shell, :path => 'ubuntu-install-docker.sh'
  config.vm.provision :shell, :path => 'ubuntu-install-docker.sh'
  config.vm.provision :shell, :path => 'ubuntu-install-jenkins.sh'

  config.vm.network "private_network", ip: "192.168.25.15"
  config.vm.hostname = "serveur-jenkins"
  # Shared folder
	config.vm.synced_folder "vagrant-rsync/", "/home/rsync", create: true
end